### /usuarios para obtener todos los usuarios
GET http://localhost:1234/usuarios

### /usuarios/:id parametro dinamico para obtener un usuario segun su id

GET http://localhost:1234/usuarios/2


### /usuarios para agregar un nuevo usuario

POST http://localhost:1234/usuarios
Content-Type: application/json

    {"id": 1,
    "nombre": "Robin Hood",
    "edad": 46,
    "email": "robin@example.com",
    "telefono": "+1 123-456-7878"}


### /usuarios/:id para modificar un usuario en especial
PATCH http://localhost:1234/usuarios/12
Content-Type: application/json

{"nombre": "Emilia"}


### /usuarios/:id para borrar un usuario en especial
DELETE http://localhost:1234/usuarios/1





